version: '2'
services:
  server:
    build:
      context: ./packages/server/
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./package/server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
      
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  client:
    build:
      context: ./packages/client/
    command: npm start
    volumes:
      - ./package/client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
